# Generated by Django 3.1 on 2020-09-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200813_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.CharField(max_length=2048, verbose_name='地址')),
                ('icon_url', models.CharField(max_length=2048, verbose_name='图标地址')),
                ('sub_title', models.CharField(max_length=200, verbose_name='副标题')),
            ],
            options={
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '博客文章'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name_plural': '配置'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '文章标签'},
        ),
    ]
